name: Quality Check

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.10

    - name: Run PEP 8 linting
      run: |
        pip install flake8
        flake8 --config .flake8 .
      continue-on-error: true

    - name: Run best practice checks
      run: |
        pip install pylint
        pylint --rcfile .pylintrc .
