name: Quality Check

on:
  push:
    branches:
      - main

jobs:
  pep8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.10

      - name: Install dependencies
        run: |
          pip install flake8
          pip install pylint

      - name: Run flake8
        run: flake8
        continue-on-error: true

      - name: Run pylint
        run: pylint .
        continue-on-error: true